dist: trusty
language: rust
services: docker
rust:
  - stable
sudo: required
env:
  global:
    - NAME=cargo-launcher

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-pc-windows-gnu

before_install:
  - rustup self update

install:
  - source ~/.cargo/env
  - cargo install --force cross

script:
  - cross test --target $TARGET --release

before_deploy:
  - cross build --target $TARGET --release
  - bin=$NAME
  - if [[ $TARGET = "x86_64-pc-windows-gnu" ]]; then bin=$NAME.exe; fi
  - tar czf $NAME-$TRAVIS_TAG-$TARGET.tar.gz -C target/$TARGET/release $bin

deploy:
  api_key:
    secure: "Mc6qcffPSHSTxHgDaYL00hzqBdhT94f8EzzCUguE6HqkRkYKdB2oRiehPIDJWoADX23p0u77BX/gdtciPjK4Xv8gRCPIUsdpOI2h91kstoaaCBRD5XXospM40qEw24jAuI/jPm4mIbEhwjFPhTqI8IQnewT5UXYpGiUxOWmqbGXsiVDC4B6hUFnghvuI2x/ZJSTeumJuUas1uY1BWHqfPiyOyXZyboOMWV9LOBA4spPmQseWED6jVxf7RX12o5aL3TRQo4So7Ho6a/5VAVWP12E1wvc5bsGRpk67BwnlgENFGn4+r3wfIe3e3d1GfqPDY80x3VpkvilL90YsuvPZgnHRF8T0Fv2F4EJWIjxHb03aVf1AM4AUjnQob9R/REJH74Y4RzJGemaUIme4FXKC9lQ4HQU8cQuMDORKFtBLmPD5akqk5eg07UGsIq+9EdX8wQiKyCwIF1VnUcmsWrb14Xd7EmMUtJN9YHaDMnuoEn/0fIaCnPRtbSxDugsFlxZHElQzUhAXDuYznUTWSPHPHxPmK6gfXptUIcVbzUSroNw4G2SCWChA9dR3+F0Ntem5hhZJ2yqvwlhIkGeICc1NecHl+5Isy2SfG5BxLNQPrnCBcpK/fhxLrHkaj/5dhqi1wCGO8UsGmbhiyktkWtIzODwnASsx6oEkDW2Y53thk3Y="
  file_glob: true
  file: $NAME-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # for release tags
    - /^v?\d+\.\d+\.\d+.*$/
    - master
